config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :users_admin, :controller => 'users', only: [:index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, except: [:new, :edit, :index]

  resources :categorizations, only: [:create, :destroy]

  get '/articles/search', to: 'articles#search', as: :articles_search

  get '/unauthorized', to: 'application#unauthorized', as: :unauthorized

  root to: "articles#index"

  resources :articles, except: [:edit, :update] do
  	resources :versions, except: [:edit, :update]
  end
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :categorizations, dependent: :destroy
	has_many :categories, through: :categorizations
	has_many :versions, dependent: :destroy
	has_many :editors, through: :versions, source: :editor

	accepts_nested_attributes_for :versions
  accepts_nested_attributes_for :categorizations

	def current_version
		versions.last
	end

  def cached_body
    versions[-2].body
  end

  def cached_title
    versions[-2].title
  end

  def editor
    current_version.editor
  end

  def edit_count
    versions.count
  end

  def last_updated_by
    editor.username
  end

  def last_updated_at
    current_version.updated_at.to_date
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :search]
	before_action :check_if_banned

	def index
		@articles = Article.joins(:versions).group("articles.id").order("count(articles.id) DESC").limit(8)
	end

	def create
		@article = Article.new(article_params)
		@article.versions[0].editor = current_user
		if @article.save
			if params[:category]
				params[:category].each do |category_id|
					Categorization.create(article: @article, category_id: category_id)
				end
			end
			redirect_to @article
		else
			@errors = @article.versions[0].errors.full_messages
			render new_article_path
		end
	end

	def new
		@article = Article.new
		@article.versions.build
		@article.categorizations.build
	end

	def show
		@article = Article.find_by(id: params[:id])
	end

	def destroy
		if admin_user?
			Article.find_by(id: params[:id]).destroy
			redirect_to articles_path
		else
			render file: "/public/422.html"
		end
	end

	def search
		@potential_matches = Article.all.map do |article|
			article.versions.last
		end
		search_term = params[:search].downcase
		@title_matches = @potential_matches.select { | version | version.title.downcase.include? search_term}
		@body_matches = @potential_matches.select { | version | version.body.downcase.include? search_term}
	end

	private
		def article_params
			params.require(:article).permit(versions_attributes: [:title, :body])
		end

end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_blurb(article)
		article.current_version.body.gsub(/(<img).*>/, "")[0..200].html_safe
	end
end

app/views/articles/_article.html.erb
<div class="panel panel-default">
	<h3><%= link_to article.current_version.title, article_path(article) %></h3>
	<p><%= article_blurb(article) %>...</p>
	<i>last updated by <%= article.last_updated_by %> on <%= article.last_updated_at %>. <%= article.edit_count %> total edit(s).</i>
</div>

app/views/articles/category.html.erb
<h3><%= link_to category.name, category_path(category) %></h3>

app/views/articles/index.html.erb
<div class="col-sm-2" id="sidebar">
  <%= render "categories/index" %>
</div>
<div class="col-sm-10" >
  <h2>Articles</h2>
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="version-form">
  <h2>Create A New Article</h2>
  <%= form_for @article do |f| %>
    <%= f.fields_for :versions do |versions_form| %>
    <div class="error">
      <% if @errors %>
      <ul>
        <% @errors.each do |error| %>
          <li> <%= error  %> </li>
          <% end %>
      </ul>
      <% end %>
    </div>
		<div>
		  <%= versions_form.label :title %>
		</div>
		<div>
		  <%= versions_form.text_field :title, class: "title-field input-lg" %>
		</div>
		<div>
		  <%= versions_form.label :body %>
		</div>
		<div>
		  <%= versions_form.cktext_area :body, rows: 10 %>
		</div>
	<% end %>
  <div>
    <%= f.fields_for :categorizations do  %>
      <%= render partial: 'categorizations/form' %>
    <% end %>
  </div>
    <br>
  	<div>
  	  <%= f.submit 'Save Article', class: "btn btn-info" %>
  	</div>
  <% end %>
   <br>
  <%= render 'categories/form' %>
</div>

app/views/articles/search.html.erb
<h3> There were <%= @title_matches.length %> searches that matched in the title!</h3>
<% @title_matches.each do |match| %>
  <%= render match.article %>
  <% end %>

<h4> There were <%= @body_matches.length %> searches that matched in the body!</h4>
<% @body_matches.each do |match| %>
	<%= render match.article %>
<% end %>

app/views/articles/show.html.erb
<div class="col-sm-2" id="sidebar">
  <%= render "categories/index" %>
</div>
<div class="col-sm-10">
	<h2><%= @article.current_version.title %></h2>
	<%= @article.current_version.body.html_safe %>
	<p><i>Last edited by <%= @article.last_updated_by %> on <%= @article.last_updated_at %>. <%= @article.edit_count %> total edit(s)</i></p>


	<h3>Categories
		<button type="button" class="btn btn-default btn-sm btn-cat">
	    <span class="glyphicon glyphicon-plus"></span> Add
	  </button>
  </h3>

  <div>
		<ul id="category-list">
		  <%= render @article.categorizations %>
		</ul>
	</div>

	<div id="categorization-form-div" style="display: none">
		<%= form_tag(controller: "categorizations", action:"create", method: "post", class: "categorization-form") do %>
			<%= hidden_field_tag(:article_id, @article.id) %>
			<%= render partial: 'categorizations/form' %>
			<%= submit_tag("Add") %>
		<% end %>
	</div>

	<%= link_to "Edit This Article", new_article_version_path(@article) if current_user %> 	|
	<%= link_to "Previous Edits", article_versions_path(@article) %>			|
	<%= link_to "Remove article", article_path(@article), method: :delete, data: { confirm: "Are you sure.  This action cannot be reversed?" } if admin_user? %>
</div>