config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :users_admin, :controller => 'users', only: [:index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, except: [:new, :edit, :index]

  resources :categorizations, only: [:create, :destroy]

  get '/articles/search', to: 'articles#search', as: :articles_search

  get '/unauthorized', to: 'application#unauthorized', as: :unauthorized

  root to: "articles#index"

  resources :articles, except: [:edit, :update] do
  	resources :versions, except: [:edit, :update]
  end
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :article
  belongs_to :category

  validates_uniqueness_of :category, :scope => :article
end

app/controllers/categorizations_controller.rb
require 'json'

class CategorizationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @categorization = Categorization.create(article_id: params[:article_id], category_id: params[:category][0])
    respond_to do |format|
      format.html { render partial: "categorization", locals: {categorization: @categorization} }
    end
  end

  def destroy
    Categorization.find_by(id: params[:id]).destroy
  end

end

app/views/categorizations/_categorization.html.erb
<li class="category-li <%= categorization.category.id %>" ><%= link_to categorization.category.name, categorization.category %>
  <% if user_signed_in? %>
    <%= link_to(categorization_path(categorization), method: :delete) do %>
      <span class="glyphicon glyphicon-minus"></span>
    <% end %>
  <% end %>
</li>

app/views/categorizations/_form.html.erb
<%= label_tag "Select all categories that apply:" %><br>
<div class="form-group">
  <%= select_tag :category, options_from_collection_for_select(Category.all, :id, :name), multiple: true, class: "form-control" %>
</div>