config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :users_admin, :controller => 'users', only: [:index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, except: [:new, :edit, :index]

  resources :categorizations, only: [:create, :destroy]

  get '/articles/search', to: 'articles#search', as: :articles_search

  get '/unauthorized', to: 'application#unauthorized', as: :unauthorized

  root to: "articles#index"

  resources :articles, except: [:edit, :update] do
  	resources :versions, except: [:edit, :update]
  end
end

app/views/shared/_nav.html.erb
<nav>
  <ul class="nav_ul">
      <li id="header" class="title"><a id="header-link" href="/">Sandbox</a></li>
      <!-- <i class="fa fa-paper-plane-o fa-lg" aria-hidden="true"></i> -->
      <li class="search-bar"><%= render '/shared/search_bar' %></li>
    <% if user_signed_in? %>
      <li class="nav-link"> <%= link_to "Homepage", root_path %> </li>
      <li class="nav-link"> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
      <li><%= link_to "New Article", new_article_path %></li>
    <% else %>
      <li class="nav-link"> <%= link_to "Homepage", root_path %> </li>
      <li class="nav-link"> <%= link_to "Login", new_user_session_path  %> </li>
      <li class="nav-link"> <%= link_to "Register", new_user_registration_path %> </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_search_bar.html.erb
<%= form_tag(articles_search_path, :method => "get", id: "search-form") do %>
		<span class="icon"><i class="fa fa-search"></i></span>
    <%= text_field_tag :search, params[:search], class: 'input-sm col-sm', placeholder: "Search Articles", minlength: 1 %>
    <%= submit_tag "Search", class: "btn btn-info", :name => nil %>
<% end %>