config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :users_admin, :controller => 'users', only: [:index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, except: [:new, :edit, :index]

  resources :categorizations, only: [:create, :destroy]

  get '/articles/search', to: 'articles#search', as: :articles_search

  get '/unauthorized', to: 'application#unauthorized', as: :unauthorized

  root to: "articles#index"

  resources :articles, except: [:edit, :update] do
  	resources :versions, except: [:edit, :update]
  end
end

app/models/version.rb
class Version < ApplicationRecord
  belongs_to :article, required: false
  belongs_to :editor, class_name: "User"

  validates :body, length: { minimum: 10 }
  validates :title, length: { minimum: 2 }
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :check_if_banned

	def index
		@article = Article.find_by(id: params[:article_id])
		@versions = @article.versions[0..-2]
	end

	def show
		@version = Version.find_by(id: params[:id])
	end

	def new
		@article = Article.find_by(id: params[:article_id])
	end

	def create
		@article = Article.find_by(id: params[:article_id])
		@version = Version.new(version_params.merge(editor: current_user, article: @article))
		if @version.save
			redirect_to article_path(@article)
		else
			@errors = @version.errors.full_messages
			render "versions/new"
		end
	end

	def destroy
		if admin_user?
			@article = Article.find_by(id: params[:article_id])
			Version.find_by(id: params[:id]).destroy
			versions_left = @article.versions.length
			redirect_to article_versions_path(@article) if versions_left > 1
			redirect_to article_path(@article) if versions_left == 1
			redirect_to articles_path if versions_left < 1
		else
			render file: "/public/422.html"
		end
	end

	private
		def version_params
			params.require(:version).permit(:title, :body)
		end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_version.html.erb
<h3> <%= version.title %></h3>
<p><%= version.body.html_safe %></p>
<p><i>written by <%= version.editor.username %> on <%= version.created_at.to_date %></i></p>
<%= link_to "Remove this version", article_version_path(version.article, version), method: :delete, data: { confirm: "Are you sure.  This action cannot be reversed?" } if admin_user? %>

app/views/versions/index.html.erb
<div class="col-sm-2" id="sidebar">
  <%= render "categories/index" %>
</div>
<div class="col-sm-10" >
  <h2>Past Versions</h2>
  <%= link_to "Back", article_path(@article) %>
  <%= render @versions %>
</div>

app/views/versions/new.html.erb
<div class="col-sm-10">
  <h2>Edit This Article</h2>
  <%= link_to "Cancel Edit", article_path(@article) %>
  <%= form_for [@article, @article.versions.build] do |f| %>
    <div class="error">
      <% if @errors %>
        <% @errors.each do |error| %>
          <%= error  %>
        <% end %>
      <% end %>
    </div>

      <div>
        <%= f.label :title %>
      </div>
      <div>
        <%= f.text_field :title, value: @article.cached_title %>
      </div>
      <div>
        <%= f.label :body %>
      </div>
      <div>
        <%= f.cktext_area :body, rows: 10, value: @article.cached_body %>
      </div>

    <div>
      <%= f.fields_for :categorizations do |categorizations_form| %>
      <div>
        <%= label_tag "Select all categories that apply:" %><br>
        <%= select_tag :category, options_from_collection_for_select(Category.all, :id, :name), multiple: true %>
      </div>
      <% end %>
    </div>
    <div>
      <%= f.submit 'Save Article' %>
    </div>
  <% end %>
</div>

app/views/versions/show.html.erb
<div class="col-sm-2" id="sidebar">
  <%= render "categories/index" %>
</div>
<div class="col-sm-10" >
  <h2>Past Versions</h2>
  <%= render @version %>
</div>